server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/testesunitarios

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345678}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

service:
  mock: false

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation